server:
   port: 8098

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/helen?useSSL=false&useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&zeroDateTimeBehavior=CONVERT_TO_NULL&serverTimezone=GMT%2B8
    username: root
    password: cheche
  redis:
    host: localhost
    password: cheche
    port: 6379
    timeout: 5000

#在映射实体或者属性时，将数据表中表名和字段名的下划线去掉，按照驼峰命名法映射
mybatis:
  configuration:
    map-underscore-to-camel-case: true


